# Generated by Django 5.0.2 on 2024-02-27 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('state_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('state_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consigner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_address', models.CharField(blank=True, max_length=512, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=30, null=True)),
                ('chasis_no', models.CharField(blank=True, max_length=30, null=True)),
                ('dl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=512, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('from_field', models.CharField(max_length=255)),
                ('to_field', models.CharField(max_length=255)),
                ('nature_of_goods', models.CharField(max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('freight_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('freight_total', models.CharField(blank=True, max_length=255, null=True)),
                ('toll_tax', models.CharField(blank=True, max_length=255, null=True)),
                ('gr_sr_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('fooding', models.CharField(blank=True, max_length=255, null=True)),
                ('kata', models.CharField(blank=True, max_length=30, null=True)),
                ('gst', models.CharField(blank=True, max_length=255, null=True)),
                ('advance', models.CharField(blank=True, max_length=255, null=True)),
                ('payable_amt', models.CharField(blank=True, max_length=255, null=True)),
                ('e_way_bill_no', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.consignee')),
                ('consigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.consigner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.vehicle')),
            ],
        ),
    ]
